# Generated by Django 5.0.2 on 2024-02-24 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("link_database", "0002_company_product_manufacturer"),
    ]

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.TextField(max_length=20, verbose_name="Полное название"),
                ),
                (
                    "short_name",
                    models.CharField(
                        max_length=20, verbose_name="Сокращенное название"
                    ),
                ),
                ("foundation_date", models.DateField(verbose_name="Дата основания")),
            ],
        ),
        migrations.RemoveField(model_name="product", name="manufacturer",),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FIO", models.TextField(verbose_name="ФИО")),
                ("born_date", models.DateField(verbose_name="Дата рождения")),
                ("get_in_year", models.DateField(verbose_name="Год поступления")),
                (
                    "university_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="link_database.university",
                        verbose_name="Университет",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Company",),
        migrations.DeleteModel(name="Product",),
    ]
