# Generated by Django 5.0.2 on 2024-02-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "link_database",
            "0003_university_remove_product_manufacturer_student_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="university_id", new_name="university",
        ),
    ]
