# Generated by Django 5.0.2 on 2024-02-24 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("link_database", "0004_rename_university_id_student_university"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="university",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="link_database.university",
                verbose_name="Университет",
            ),
            preserve_default=False,
        ),
    ]
